name: GitHub Downloader
# Define when to run job here
on: [push, pull_request]

jobs:
  example_job:
    runs-on: ubuntu-latest
    name: Runing Github Downloader
    steps:
    - uses: actions/checkout@v2


     # Commit the updates
    - name: Commit and Push Downloaded Files 
      run: |
         git mv trunks* /.
         git add * 
         git commit -m "Folders moved out of webapp directory :-)"
